now the project uuid can be used

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,15 +4,15 @@ inputs:
   dt-url:
     description: 'The URL of the Dependency-Track API server to send the SBOM to OWASP Dependency Track Server'
     required: true
-  api-key:
-    description: 'The API key used to authenticate with the Dependency-Track API server.'
-    required: true
   project-name:
     description: 'Project name.'
-    required: true
+    required: false
   project-version:
     description: 'Project version.'
-    required: true
+    required: false
+  project-uuid:
+    description: 'Project UUID can be provided instead of project name and version.'
+    required: false
   path-to-sbom:
     description: 'path to the sbom to upload.'
     required: true
@@ -20,39 +20,67 @@ runs:
   using: "composite"
   steps:
     - run: |
-          API_ENDPOINT="${{ inputs.dt-url }}/api/v1/project/lookup"
-          API_KEY="${{ inputs.api-key }}"
-          PROJECT_NAME="${{ inputs.project-name }}"
-          PROJECT_VERSION="${{ inputs.project-version }}"
+            API_ENDPOINT="${{ inputs.dt-url }}/api/v1/project/lookup"
+            API_KEY="${{ secrets.DEPENDENCYTRACK_APIKEY }}"
+            PROJECT_NAME="${{ inputs.project-name }}"
+            PROJECT_VERSION="${{ inputs.project-version }}"
+            NEW_SBOM="${{ inputs.path-to-sbom }}"
+            UUID="${{ inputs.project-uuid }}"
 
-          response=$(curl -k -X GET  -H "X-Api-Key: $API_KEY" "$API_ENDPOINT?name=$PROJECT_NAME&version=$PROJECT_VERSION")
+            if [ -z "$UUID" ]; then
+                if [ -z "$PROJECT_NAME" ] || [ -z "$PROJECT_VERSION" ]; then
+                    echo "Error: Either UUID or both project name and version must be provided."
+                    exit 1
+                fi
 
-          if echo "$response" | jq -e '.uuid' > /dev/null; then
-          uuid=$(echo "$response" | jq -r '.uuid')
-          echo "UUID: $uuid"
-          # API request to retrieve the existing SBOM
-          curl -k -X GET -H "X-Api-Key: $API_KEY" "${{inputs.dt-url}}/api/v1/bom/cyclonedx/project/${uuid}?format=json&variant=withVulnerabilities&download=true" > existing_sbom.json| jq '.'
-          else
-              uuid=""
-               echo '{}' > existing_sbom.json
-          fi
+                echo "GET project UUID"
+                response=$(curl -k -X GET  -H "X-Api-Key: $API_KEY" "$API_ENDPOINT?name=$PROJECT_NAME&version=$PROJECT_VERSION")
+
+                if echo "$response" | jq -e '.uuid' > /dev/null; then
+                    UUID=$(echo "$response" | jq -r '.uuid')
+                    echo "UUID: $UUID"
+                else
+                    echo "Couldn't retrieve project UUID, an error occured: $response"
+                    exit 1
+                fi
+            else
+                echo "UUID provided: $UUID. Skipping project lookup."
+            fi
+
+            echo "GET existing SBOM from Dependency Track"
+            response=$(curl -k -X GET -H "X-Api-Key: $API_KEY" "${{inputs.dt-url}}/api/v1/bom/cyclonedx/project/${UUID}?format=json&variant=withVulnerabilities&download=true")
+
+            if echo "$response" | jq -e '.errors' > /dev/null; then
+                echo "Error: Couldn't retrieve existing SBOM. Error message: $response"
+                exit 1
+            else
+                echo "Existing SBOM retrieved from Dependency Track"
+                echo "$response" | jq '.'
+            fi
       shell: bash
     - run: |
-            jq -s 'def deepmerge(a;b):
-             reduce b[] as $item (a;
-                reduce ($item | keys_unsorted[]) as $key (.;
-                  $item[$key] as $val | ($val | type) as $type | .[$key] = if ($type == "object") then
-                    deepmerge({}; [if .[$key] == null then {} else .[$key] end, $val])
-                  elif ($type == "array") then
-                   (.[$key] + $val | unique)
-                  else
-                    $val
-                  end)
-                );
-            deepmerge({}; .)' bom.json existing_sbom.json > aggregated_sbom.json
+            if [ -f existing_sbom.json ]; then
+                echo "Merging the existing and new SBOMs"
+                jq -s 'def deepmerge(a;b):
+                 reduce b[] as $item (a;
+                    reduce ($item | keys_unsorted[]) as $key (.;
+                      $item[$key] as $val | ($val | type) as $type | .[$key] = if ($type == "object") then
+                        deepmerge({}; [if .[$key] == null then {} else .[$key] end, $val])
+                      elif ($type == "array") then
+                       (.[$key] + $val | unique)
+                      else
+                        $val
+                      end)
+                    );
+                deepmerge({}; .)' $NEW_SBOM existing_sbom.json > aggregated_sbom.json
+                echo "Merged"
+            else
+                echo "No existing SBOM found. Skipping merge operation."
+                cp $NEW_SBOM aggregated_sbom.json
+            fi
       shell: bash
     - run: |
-          # Read the combined JSON content from the file
+          echo "encode the combined SBOM JSON and build payload"
           encoded_sbom=$(jq -c . aggregated_sbom.json | base64 | tr -d '\n')
           payloadfile=$(mktemp)
 
@@ -75,13 +103,12 @@ runs:
           EOF
             fi
 
-          # API request to upload the aggregated SBOM to Dependency Track
+          echo " PUT aggregated SBOM to Dependency Track"
           curl -k -X PUT "${{ inputs.dt-url }}/api/v1/bom" \
             -H "Content-Type: application/json" \
             -H "X-Api-Key: ${{ inputs.api-key }}" \
             -d @"$payloadfile"
-
       shell: bash
     - run: |
-          rm "bom.json" "existing_sbom.json" "aggregated_sbom.json"
+          rm "existing_sbom.json" "aggregated_sbom.json"
       shell: bash
